openapi: 3.0.0
info:
  title: NFT Trading API
  version: 2.0
servers:
  - url: /
paths:
  /api:
    get:
      summary: Welcome message
      responses:
        '200':
          description: Welcome message
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                walletAddress:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid request payload
  # Add other paths for your API endpoints
